---
title: "TCG_FinalProject_Phase1"
author: "Layeeq Mohammed & Pooja Awasthi"
date: "22 April 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
library(rvest)
library(plyr)
library(lubridate)
library(ggplot2)
library(cluster)

#Model 1: In this model,we considered X- Axis as 'comm_rate'(Company Rate), Y-Axis as 'ind_rate'(Industry Rate) 
#of the towns across the cities, to plot the variation of different prices of comm_rate and ind_rate. 
#The interpreted coefficients holds everything in the model constant and the mean gets decreasing, i.e Adjusted R-squared:  0.05222 


urllink <- read.csv("https://raw.githubusercontent.com/poojaawasthi13/TCG_FinalProject/master/noniouzipcodes2015.csv",header=TRUE, sep=",")
data <- data.frame(urllink)
data

model_1 <- lm(ind_rate ~ comm_rate, data = data)
summary(model_1)


data$predicted <- predict(model_1)   
data$residuals <- residuals(model_1) 
data

ggplot(data, aes(x = comm_rate , y = ind_rate)) +
  geom_point() +
  geom_point(aes(y = predicted), shape = 1)
ggplot(data, aes(x = comm_rate , y = residuals, color=comm_rate)) +
  geom_point() +
  geom_segment(aes(xend = comm_rate , yend = 0), alpha = .2) + geom_hline(yintercept = 0)

```

```{r}
library(rvest)
library(plyr)
library(lubridate)
library(ggplot2)
library(cluster)

#Model 2: In this model,we considered X- Axis as 'comm_rate'(Company Rate) + 'res_rate'(Residential Rate), Y-Axis as 'ind_rate'(Industry Rate) 
#of the towns across the cities, to plot the variation of different prices of comm_rate, res_rate and ind_rate .
#The interpreted coefficients holds everything in the model constant and the mean gets decreasing, i.e Adjusted R-squared:  0.05582

model_2 <- lm(ind_rate ~ comm_rate + res_rate, data = data)
summary(model_2)
data$predicted <- predict(model_2)   
data$residuals <- residuals(model_2) 
data
ggplot(data, aes(x = comm_rate + res_rate, y = ind_rate)) +
  geom_point() +
  geom_point(aes(y = predicted), shape = 1)
ggplot(data, aes(x = comm_rate, y = residuals, color=ind_rate)) +
  geom_point() +
  geom_segment(aes(xend = comm_rate , yend = 0), alpha = .2) + geom_hline(yintercept = 0)
```

```{r}
library(rvest)
library(plyr)
library(lubridate)
library(ggplot2)
library(cluster)

#Model 3: In this model, we considered X- Axis as 'comm_rate'(Company Rate) + 'res_rate'(Residential Rate), 
#Y-Axis as 'ind_rate' (Industry Rate)' of the towns across the cities, to plot the variation of different prices of comm_rate, res_rate and ind_rate . 
#The interpreted coefficients holds everything in the model constant and the mean gets increasing and 
#It is the best model compared to other 2 previous models because it has higher value of Adjusted R-squared: 0.9327 

model_3 <- lm(ind_rate ~ comm_rate + res_rate + factor(eiaid), data = data)
summary(model_3)
data$predicted <- predict(model_3)   
data$residuals <- residuals(model_3) 
data
ggplot(data, aes(x = comm_rate + res_rate, y = ind_rate)) +
  geom_point() +
  geom_point(aes(y = predicted), shape = 1)
ggplot(data, aes(x = comm_rate + res_rate , y = residuals, color=res_rate))  +
  geom_point() +
  geom_segment(aes(xend = comm_rate + res_rate , yend = 0), alpha = .2) + geom_hline(yintercept = 0)

```

